import openmeteo_requests
import requests_cache
import pandas as pd
from retry_requests import retry
import os

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

target_locations = {
    "Delhi": {"Anand_Vihar": (28.6476, 77.3158), "RK_Puram": (28.5651, 77.1751), "ITO": (28.6286, 77.2410)},
    "Mumbai": {"Bandra_Kurla_Complex": (19.0535, 72.8464), "Colaba": (18.9100, 72.8200), "Worli": (19.0001, 72.8140)},
    "Bengaluru": {"City_Railway_Station": (12.9733, 77.5670), "Silk_Board": (12.9176, 77.6233), "Peenya_Industrial_Area": (13.0329, 77.5273)}
}

url = "https://archive-api.open-meteo.com/v1/archive"
all_weather_records = []

for city, locations in target_locations.items():
    print(f"\n========== Fetching historical weather for {city} ==========")
    for location_name, (lat, lon) in locations.items():
        print(f"  -> Downloading 30 days of hourly data for {location_name}...")
        
        params = {
            "latitude": lat,
            "longitude": lon,
            "start_date": "2026-01-15", # Adjust to match your OpenAQ dates
            "end_date": "2026-02-15",
            "hourly": ["temperature_2m", "relative_humidity_2m", "surface_pressure", "wind_speed_10m", "wind_direction_10m"]
        }
        
        responses = openmeteo.weather_api(url, params=params)
        response = responses[0]
        hourly = response.Hourly()
        
        # Create a dataframe for this specific location
        hourly_data = {"timestamp_utc": pd.date_range(
            start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
            end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
            freq = pd.Timedelta(seconds = hourly.Interval()),
            inclusive = "left"
        )}
        hourly_data["city"] = city
        hourly_data["location"] = location_name
        hourly_data["temperature_c"] = hourly.Variables(0).ValuesAsNumpy()
        hourly_data["humidity_percent"] = hourly.Variables(1).ValuesAsNumpy()
        hourly_data["pressure_hpa"] = hourly.Variables(2).ValuesAsNumpy()
        hourly_data["wind_speed_mps"] = hourly.Variables(3).ValuesAsNumpy()
        hourly_data["wind_direction_deg"] = hourly.Variables(4).ValuesAsNumpy()

        df_loc = pd.DataFrame(data = hourly_data)
        all_weather_records.append(df_loc)

# Combine all locations into one massive dataset
df_final = pd.concat(all_weather_records, ignore_index=True)

# Drop any blank rows generated by the API
df_final = df_final.dropna()

os.makedirs("data", exist_ok=True)
df_final.to_csv("data/India_3city_weather.csv", index=False)
print(f"\nSuccess! Saved {len(df_final)} rows of weather data.")